### PR TITLE
UX Fun Task Completed

### PR DESCRIPTION
**Pull request by ad8ya089**
Issue : #63 
UX fun task Completed successfully

### CODE REVIEW

**Comment by hridayesh-arya** [comment]
@ad8ya089 Looks like you chatgptd the already chatgptd content to make it look less chatgptd 😂

**Comment by ad8ya089** [comment]
@hridayesh-arya I wrote it myself this time, check the Ai content if u have any doubt.

**Comment by hridayesh-arya** [comment]
@ad8ya089 Somehow these two versions looks same to me.  🙃
image
image

I appreciate your efforts, and after all, you did complete the game!
So, I’m merging your PR. ✨

Keep learning, keep contributing, and keep open-coding! 🔥

**Comment by ad8ya089** [comment]
@hridayesh-arya Thanks buddy, I was writing that part in the previous doc so it is present there.

**Pull request merged**
